### ISSUE TITLE
Django-click doesn't work with click >= 7.1

### ISSUE THREAD

**Issue by ykshatroff** [GaretJax/django-click#14]
When installing a version of `click` later than 7.0, the djclick import fails with an error:
```
    import djclick
/usr/local/lib/python3.6/site-packages/djclick/__init__.py:16: in <module>
    __all__ = click.__all__ + ['pass_verbosity']
E   AttributeError: module 'click' has no attribute '__all__'
```
The `click` module does not define `__all__` as of 7.1 and later.

**Comment by rafaph** [comment]
Seems like removing this line

```python
__all__ = click.__all__ + ['pass_verbosity']
```

Solve the problem

**Comment by pkfec** [comment]
With the following latest packages, I am getting` AttributeError: module 'click' has no attribute '__all__'`
How I can resolve this issue?  

django v2.2.11
python v3.7.5
click v7.1.1
django-click v2.1.0

**Comment by ykshatroff** [comment]
@pkfec Unfortunately, it is not easy. 

I suggest that for the time being, while this issue is not fixed by a new release, you fork this repository and install the package directly from your git. (Please refer to the respective docs for `pip` or `pipenv` or whatever package manager you're using, as to how exactly to do it.)

All you need to change is to delete this line: https://github.com/GaretJax/django-click/blob/master/djclick/__init__.py#L16

But a new release is blocked by failing tests and a bunch of pretty old unsupported dependencies.

**Comment by D3f0** [comment]
@ykshatroff won't removing all kill autocompletion in completion-capable editors? I know after some time you learn click options/arguments by heart, but even so, some inner things like pass_context require some "Go to definition" :blush:

**Comment by ykshatroff** [comment]
@D3f0 
Well first, what is more important: autocompletion in editors or a working library? :)
Second, if the dependency doesn't provide us with their `__all__` where are we supposed to take it from? I don't feel like we should build our own `__all__` for `click`. And in any case, it must have been removed for a reason - which, I suppose, is that `__all__` is no longer a thing for autocompletion in
